# permissions for end users to view autoingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoingress-viewer-role
rules:
- apiGroups:
  - apps.ingress.com
  resources:
  - autoingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.ingress.com
  resources:
  - autoingresses/status
  verbs:
  - get
