# permissions for end users to edit autoingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoingress-editor-role
rules:
- apiGroups:
  - apps.ingress.com
  resources:
  - autoingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.ingress.com
  resources:
  - autoingresses/status
  verbs:
  - get
